version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - blog_network

  webserver:
    image: nginx:alpine
    container_name: blog_webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - blog_network

  db:
    image: mysql:8.0
    container_name: blog_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - blog_network

  redis:
    image: redis:alpine
    container_name: blog_redis
    restart: unless-stopped
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge

volumes:
  dbdata:
    driver: local